version: '3'

services:
  janus-gateway:
    image: iorikingdom/janus:latest
    ports:
      - "7777:80"
      - "443:443"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}
